// ╔════════════════════════════════════════════════════════════════════╗
// ║  MODULE: SOIL SCIENCE                                             ║
// ╚════════════════════════════════════════════════════════════════════╝

modules.push({
  id:       'soil',
  icon:     '🪨',
  category: 'soil',
  title:       { en: 'Soil Science',       fr: 'Science du Sol',      ar: 'علم التربة' },
  description: { en: 'Comprehensive study of soil composition, physics, chemistry, and biology.',
                 fr: 'Étude complète de la composition, physique, chimie et biologie des sols.',
                 ar: 'دراسة شاملة لتركيب التربة وفيزيائها وكيميائها وأحيائها.' },

  books: [
    { icon: '📕',
      title:  { en: 'Guide des analyses en pédologie: 2e édition', fr: 'Guide des analyses en pédologie: 2e édition', ar: 'Guide des analyses en pédologie: 2e édition' },
      author: { en: 'Denis Baize - 2000', fr: 'Denis Baize - 2000', ar: 'Denis Baize - 2000' },
      langs: ['fr'], cover:  'files/images/books/soil/GSP.jpg',
      file:   'https://drive.google.com/file/d/1dVsn_mfVA7oAh-X0QmRO8RY-Iswuz6Zu/view?usp=drive_link' },

    { icon: '📕',
      title:  { en: "L'analyse du sol: échantillonnage, instrumentation et contrôle", fr: "L'analyse du sol: échantillonnage, instrumentation et contrôle", ar: "L'analyse du sol: échantillonnage, instrumentation et contrôle" },
      author: { en: 'Marc Pansu et al - 1997', fr: 'Marc Pansu et al - 1997', ar: 'Marc Pansu et al - 1997' },
      langs: ['fr'], cover:  'files/images/books/soil/AEIC.jpg',
      file:   'https://drive.google.com/file/d/1nzz07UtqwjS4HTcaAjCi4tBREHAuotIr/view?usp=drive_link' },
    
      { icon: '📕',
      title:  { en: 'Fundamentals of Soil Science: 8th Edition', fr: 'Fundamentals of Soil Science: 8th Edition', ar: 'Fundamentals of Soil Science: 8th Edition' },
      author: { en: 'Henry D. Foth - 1990', fr: 'Henry D. Foth - 1990', ar: 'Henry D. Foth - 1990' },
      langs: ['en'], cover:  'files/images/books/soil/FOSS8E.jpg',
      file:   'https://drive.google.com/file/d/1pSi9uIePdH0t3SlF9F3gVGZS2cV7WDzk/view?usp=drive_link' },
    
  ],


  subModules: [

    // ── Sub: Soil Physics ──────────────────────
    {
      id: 'soil-physics', icon: '⚡', category: 'physics',
      title:       { en: 'Soil Physics',       fr: 'Physique du Sol',     ar: 'فيزياء التربة' },
      description: { en: 'Physical properties and processes of soils: texture, structure, porosity, and water movement.',
                     fr: "Propriétés physiques et processus des sols : texture, structure, porosité et mouvement de l'eau.",
                     ar: 'الخصائص الفيزيائية للتربة وعملياتها: القوام والبنية والمسامية وحركة الماء.' },
      books: [], courseFiles: [], exercises: [],
      topics: [
        { id: 'mass-volume', icon: '📐', order: 1,
          title:       { en: 'Mass-Volume Relations', fr: 'Relations Masse-Volume', ar: 'علاقات الكتلة-الحجم' },
          description: { en: 'Density, porosity, void ratio, and phase relationships.',  fr: 'Densité, porosité, indice des vides et relations entre phases.',  ar: 'الكثافة والمسامية ونسبة الفراغات والعلاقات بين الأطوار.' },
          explanation: 'files/explanations/soil/physic/mass-volume/mass-volume', 
          videoId: '', playlist: '',
          courseFiles: [], books: [], 
          exercises: [
            { icon: '📝', type: 'tp', 
              title: { en: 'TP1: Soil Density and Porosity Analysis', fr: 'TP1: Analyse de la densité et de la porosité du sol', ar: 'TP1: تحليل كثافة ومساميّة التربة' }, 
              langs: ['fr'], videoId: '', file: '' },
          ],
          quizzes: [
            { icon: '📝', title: { en: 'Mass-Volume Quiz', fr: 'Quiz Masse-Volume', ar: 'اختبار الكتلة-الحجم' },
              questions: 58, chapters: 7, langs: ['EN', 'FR', 'AR'],
              file: 'https://www.mediafire.com/file/msfqgmnb6fzdern/SOIL_PHYSICS_-_CH01_Soil_Components.json/file' },
          ],
        },
        { id: 'texture', icon: '🧱', order: 2,
          title:       { en: 'Soil Texture',       fr: 'Texture du Sol',     ar: 'قوام التربة' },
          description: { en: 'Particle size distribution and textural classification of soils.', fr: 'Distribution granulométrique et classification texturale des sols.', ar: 'توزيع حجم الحبيبات والتصنيف القوامي للتربة.' },
          explanation: 'files/explanations/soil/physic/texture/texture',
          videoId: '', playlist: '',
          courseFiles: [], books: [],
          exercises: [
            { icon: '📝', type: 'td', 
              title: { en: 'TD 1: Textural Triangle', fr: 'TD 1: Triangle Textural', ar: 'TD 1: مثلث القوام' }, 
              langs: ['fr'], videoId: '', file: '' },
          ],
          quizzes: [
            { icon: '📝', title: { en: 'Soil Texture Quiz', fr: 'Quiz Texture du Sol', ar: 'اختبار قوام التربة' },
              questions: 34, chapters: 5, langs: ['EN', 'FR', 'AR'],
              file: 'https://www.mediafire.com/file/ap8vxhl3fkwtb4l/SOIL_PHYSICS_-_CH02_Soil_Texture.json/file' },
          ],
        },
        { id: 'structure', icon: '🏗️', order: 3,
          title:       { en: 'Soil Structure',     fr: 'Structure du Sol',   ar: 'بنية التربة' },
          description: { en: 'Aggregation, pore space, and structural classification.', fr: 'Agrégation, espace poreux et classification structurale.', ar: 'التجمع والفراغات المسامية والتصنيف البنيوي.' },
          explanation: 'files/explanations/soil/physic/structure/structure',
          videoId: '', playlist: '',
          courseFiles: [], books: [], exercises: [], quizzes: [],
        },
        { id: 'porosity', icon: '🌐', order: 4,
          title:       { en: 'Soil Porosity',      fr: 'Porosité du Sol',    ar: 'مسامية التربة' },
          description: { en: 'Macro/meso/micropores, total vs effective porosity, pore size distribution', fr: 'Macro/méso/micro-pores, porosité totale vs porosité effective, distribution granulométrique des pores', ar: 'المسام الكبيرة/المتوسطة/الصغيرة، المسامية الكلية مقابل المسامية الفعالة، توزيع حجم المسام' },
          explanation: 'files/explanations/soil/physic/porosity/porosity', videoId: '', playlist: '',
          courseFiles: [], books: [], exercises: [], quizzes: [],
        },
        { id: 'water', icon: '💧', order: 5,
          title:       { en: 'Soil Water',         fr: 'Eau du Sol',         ar: 'ماء التربة' },
          description: { en: 'Water retention, movement, and soil moisture characteristics.', fr: "Rétention d'eau, mouvement et caractéristiques d'humidité du sol.", ar: 'احتباس الماء وحركته وخصائص رطوبة التربة.' },
          explanation: 'files/explanations/soil/physic/soil-water/water', videoId: '', playlist: '',
          courseFiles: [], books: [], exercises: [], quizzes: [],
        },
      ],
    },

    // ── Sub: Soil Chemistry ────────────────────
    {
      id: 'soil-chemistry', icon: '⚗️', category: 'chemistry', 
      title:       { en: 'Soil Chemistry',     fr: 'Chimie du Sol',      ar: 'كيمياء التربة' },
      description: { en: 'Chemical properties, reactions, and nutrient dynamics in soils.',
                     fr: 'Propriétés chimiques, réactions et dynamique des nutriments dans les sols.',
                     ar: 'الخصائص الكيميائية والتفاعلات وديناميكية العناصر الغذائية في التربة.' },
      books: [], exercises: [],
      courseFiles: [
        { icon: '📄', title: { en: 'Soil Chemistry - University of Biskra', fr: 'Chimie du sol - Université de Biskra', ar: 'كيمياء التربة - جامعة بسكرة' },
          file: 'https://drive.google.com/drive/folders/1lJt4nuSiKuxAFPn46Lv2ybV5m4OCAKs5?usp=drive_link' },
      ],
      topics: [
        { id: 'soil-solution', icon: '💧', order: 1,
          title:       { en: 'Soil Solution',     fr: 'Solution du Sol',    ar: 'محلول التربة' },
          description: { en: 'Water polarity, hydration, hydrolysis, amphoteric nature, composition.', fr: 'Polarité de l\'eau, Hydratation, Hydrolyse, Nature Amphotère, Composition.', ar: 'قطبية الماء، الترطيب، التحلل المائي، الطبيعة المتذبذبة، التركيب.' },
          explanation: 'files/explanations/soil/chemic/soil-solution/soil-solution', videoId: '', playlist: '',
          courseFiles: [], books: [], exercises: [], quizzes: [],
        },
        { id: 'ion-exchange', icon: '🔄', order: 2,
          title:       { en: 'Ion Exchange Capacity',     fr: 'Capacité d\'Échange d\'Ionique',    ar: 'قدرة التبادل الأيوني' },
          description: { en: 'CEC, AEC, exchange complex, selectivity, base saturation.', fr: 'CEC, AEC, complexe d\'échange, sélectivité, saturation de base.', ar: 'CEC، AEC، مركب التبادل، الانتقائية، تشبع القاعدة.' },
          explanation: 'files/explanations/soil/chemic/iec/ion-exchange', videoId: '', playlist: '',
          courseFiles: [], books: [], exercises: [], quizzes: [],
        },
        { id: 'soil-ph', icon: '🧪', order: 3,
          title:       { en: 'Soil pH',     fr: 'pH du Sol',    ar: 'محلول التربة' },
          description: { en: 'Definition, measurement, buffering capacity, pH effect on nutrient availability.', fr: 'Définition, Mesure, Povoir Tampon, Effet du pH sur la disponibilité des nutriments.', ar: 'التعريف، القياس، القدرة على التخزين المؤقت، تأثير الرقم الهيدروجيني على توفر المغذيات.' },
          explanation: 'files/explanations/soil/chemic/soil-ph/soil-ph', videoId: '', playlist: '',
          courseFiles: [], books: [], exercises: [], quizzes: [],
        },
      ],
    },

    // ── Sub: Soil Biology ──────────────────────
    {
      id: 'soil-biology', icon: '🐌', category: 'soilbiology',
      title:       { en: 'Soil Biology',       fr: 'Biologie du sol',    ar: 'بيولوجيا التربة' },
      description: { en: 'Living organisms in soil and their roles', fr: 'Organismes vivants du sol et leurs rôles', ar: ' الكائنات الحية في التربة وأدوارها' },
      books: [
        { icon: '📕',
      title:  { en: 'La Faune des Sols, son écologie et son action', fr: 'La Faune des Sols, son écologie et son action', ar: 'La Faune des Sols, son écologie et son action' },
      author: { en: 'Georges Bachelier - 1978', fr: 'Georges Bachelier - 1978', ar: 'Georges Bachelier - 1978' },
      langs: ['fr'], cover:  'files/images/books/soil/FSEA.jpg',
      file:   'https://drive.google.com/file/d/1lV8BaZNpgq0-AjTjXQugvivrIKv-8Kux/view?usp=sharing' },
      { icon: '📕',
      title:  { en: 'Biology of Soil Science', fr: 'Biology of Soil Science', ar: 'Biology of Soil Science' },
      author: { en: ' Charlotte Jhonson - 2009', fr: 'Charlotte Jhonson - 2009', ar: 'Charlotte Jhonson - 2009' },
      langs: ['en'], cover:  'files/images/books/soil/BoSS.jpg',
      file:   'https://drive.google.com/file/d/1YvkngNxxGpJg1mGsIjvuyjggszhAOcDj/view?usp=drive_link' },
      { icon: '📕',
      title:  { en: 'Soil Microbiology, Ecology and Biochemistry: 4th Edition', fr: 'Soil Microbiology, Ecology and Biochemistry: 4th Edition', ar: 'Soil Microbiology, Ecology and Biochemistry: 4th Edition' },
      author: { en: ' Eldor Paul - 2015', fr: 'Eldor Paul - 2015', ar: 'Eldor Paul - 2015' },
      langs: ['en'], cover:  'files/images/books/soil/SMEaB.jpg',
      file:   'https://drive.google.com/file/d/1KaPXQAXxzd9xcJHnxHZCS5TfQowwmToh/view?usp=drive_link' },
      
      ], courseFiles: [], exercises: [],
      topics: [
        { id: 'fauna', icon: '🐍', order: 1,
          title:       { en: 'Soil Fauna',       fr: 'Faune du Sol',      ar: 'حيوانات التربة' },
          description: { en: 'Microfauna, Mesofauna , Macrofauna', fr: 'Microfaune, Mésofaune, Macrofaune', ar: 'الميكروفونة ، الميزوفونة ، الماكروفونة' },
          explanation: 'files/explanations/soil/biology/fauna/fauna', videoId: '', playlist: '',
          courseFiles: [], books: [], exercises: [], quizzes: [],
        },
        { id: 'flora', icon: '🍃', order: 2,
          title:        { en: 'Soil Microorganisms (Flora)', fr: 'Microorganismes du Sol (Flore)', ar: 'الكائنات الدقيقة (الميكروفلورا)' },
          description: { en: 'Bacteria, fungi, actinomycetes, algae — roles, biomass, diversity', fr: 'Bactéries, champignons, actinomycètes, algues — rôles, biomasse, diversité', ar: 'البكتيريا والفطريات والفطريات الشعاعية والطحالب — الأدوار والكتلة الحيوية والتنوع' },
          explanation: 'files/explanations/soil/biology/flora/microorganisms', videoId: '', playlist: '',
          courseFiles: [], books: [], exercises: [], quizzes: [],
        },
        { id: 'decomposition', icon: '♻️', order: 3,
          title: { en: 'Decomposition & Mineralization', fr: 'Décomposition & Minéralisation', ar: 'التحلل والتمعدن' },
          description: { en: 'Organic matter breakdown, C/N ratio effect, nutrient release.', fr: 'Décomposition MO, effet C/N, libération des nutriments.', ar: 'تحلل المادة العضوية، تأثير C/N، إطلاق العناصر.' },
          explanation: 'files/explanations/soil/biology/decomposition/decomposition', videoId: '', playlist: '', courseFiles: [], books: [], exercises: [], quizzes: [],
        },
      ],
    },

    // ── Sub: Soil Fertility ────────────────────
    {
      id: 'soil-fertility', icon: '🌱', category: 'fertility',
      title:       { en: 'Soil Fertility',     fr: 'Fertilité du Sol',   ar: 'خصوبة التربة' },
      description: { en: "Study of the soil's capacity to supply essential nutrients to plants.", fr: "Étude de la capacité du sol à fournir les éléments nutritifs nécessaires.", ar: 'دراسة قدرة التربة على تزويد النباتات بالعناصر الغذائية الضرورية' },
      books: [
        { icon: '📕', title: { en: 'Plant Nutrition and Soil Fertility', fr: 'Plant Nutrition and Soil Fertility', ar: 'Plant Nutrition and Soil Fertility' },
              author: { en: 'OUALI Abdelouahad', fr: 'OUALI Abdelouahad', ar: 'والي عبد الواحد' },
              langs: ['en'], cover: 'files/images/books/soil/PNSF.jpg', file: 'https://drive.google.com/file/d/1dVsn_mfVA7oAh-X0QmRO8RY-Iswuz6Zu/view?usp=drive_link' },
        { icon: '📕',
              title:  { en: 'Fertilisation et Amendements: dossier d\’autoformation', fr: 'Fertilisation et Amendements: dossier d\’autoformation', ar: 'Fertilisation et Amendements: dossier d\’autoformation' },
              author: { en: 'ENESAD (Madeleine Asdrubal) - 2006', fr: 'ENESAD (Madeleine Asdrubal) - 2006', ar: 'ENESAD (Madeleine Asdrubal) - 2006' },
              langs: ['fr'], cover:  'files/images/books/soil/FeA.jpg', file:   'https://drive.google.com/file/d/1_SyIuwAxuLTHxjCffsklZkXc0hc5b4rZ/view?usp=drive_link' },
      ], exercises: [],
      courseFiles: [
        { icon: '📄', title: { en: 'Soil Fertility - University of Biskra', fr: 'Fertilité du Sol - Université de Biskra', ar: 'خصوبة التربة - جامعة بسكرة' },
          langs: ['fr'], file: 'https://drive.google.com/drive/folders/1nnhfQanETTLSt0wIYn1phRd5hCFjBaKh?usp=drive_link' },
        { icon: '📄', title: { en: 'Soil Fertility - National Higher School of Agronomy', fr: 'Fertilité du Sol - École Nationale Supérieure Agronomique', ar: 'خصوبة التربة - المدرسة الوطنية العليا للزراعة' },
          langs: ['fr'], file: 'https://drive.google.com/drive/folders/1zSa3wob7JidAJUXm9wOqaca3Ghesbu1Z?usp=drive_link' },
      ],
      topics: [
        { id: 'fertility-concepts', icon: '💡', order: 1,
          title: { en: 'Soil Fertility Concepts', fr: 'Concepts de Fertilité', ar: 'مفاهيم الخصوبة' },
          description: { en: 'Natural vs acquired fertility, Liebig\'s law, limiting factors.', fr: 'Fertilité naturelle vs acquise, loi de Liebig, facteurs limitants.', ar: 'الخصوبة الطبيعية مقابل المكتسبة، قانون ليبيغ، العوامل المحددة.' },
          explanation: 'files/explanations/soil/fertility/fertility-concepts/fertility-concepts', videoId: '', playlist: '', courseFiles: [], books: [], exercises: [], quizzes: [],
        },
        { id: 'fertilisation', icon: '🥀', order: 2,
          title:       { en: 'Fertilisation',    fr: 'Fertilisation',     ar: 'التخصيب' },
          description: { en: 'Organic vs mineral fertilizers, NPK calculation, application methods', fr: 'Engrais organiques vs engrais minéraux, calcul NPK, méthodes d\'application', ar: 'الأسمدة العضوية مقابل الأسمدة المعدنية، حساب NPK، طرق الاستخدام' },
          explanation: 'files/explanations/soil/fertility/fertilisation/fertilisation', videoId: 'FP_nltHwsCo',
          playlist: 'https://www.youtube.com/watch?v=FP_nltHwsCo&list=PLpot-tBGux4n6R8PU9Zc3Pao1Td4HUL-L',
          courseFiles: [], books: [], exercises: [], quizzes: [],
        },
        { id: 'soil-amendments', icon: '✨', order: 3,
          title: { en: 'Soil Amendments', fr: 'Amendements du Sol', ar: 'محسنات التربة' },
          description: { en: 'Lime, gypsum, organic amendments, biochar.', fr: 'Chaux, gypse, amendements organiques, biochar.', ar: 'الجير والجبس والمحسنات العضوية والفحم الحيوي.' },
          explanation: 'files/explanations/soil/fertility/soil-amendments/amendments', videoId: '', playlist: '', courseFiles: [], books: [], exercises: [], quizzes: [],
        },
      ],
    },

    // ── Sub:  Pedology (Soil Formation & Classification) ────────────────────
    {
      id: ' Pedology', icon: '🗺️', category: ' soil',
      title:       { en: ' Pedology',     fr: 'Pedologie',   ar: 'علم التربة' },
      description: { en: "Soil Formation & Classification.", fr: "Formation et classification des sols.", ar: 'تكوين التربة وتصنيفها' },
      books: [
         { icon: '📕',
      title:  { en: 'Soil Formation', fr: 'Soil Formation', ar: 'Soil Formation' },
      author: { en: 'Nico Van Breemen, Peter Buurman - 2002', fr: 'Nico Van Breemen, Peter Buurman - 2002', ar: 'Nico Van Breemen, Peter Buurman - 2002' },
      langs: ['en'], cover:  'files/images/books/soil/SF2E.jpg',
      file:   'https://drive.google.com/file/d/1lV8BaZNpgq0-AjTjXQugvivrIKv-8Kux/view?usp=sharing' },
      
      ], exercises: [], courseFiles: [],
      topics: [
        { id: 'soil-forming-factors', icon: '🌍', order: 1,
          title:       { en: 'Soil Forming Factors',    fr: 'Facteurs de formation des sols',     ar: 'عوامل تكوين التربة' },
          description: { en: 'Climate, Organisms, Relief, Parent material, Time', fr: 'Climat, Organismes, Relief, Matériau Parental, Temps', ar: ' المناخ، الكائنات الحية، التضاريس، المواد الأصلية، الزمن ' },
          explanation: 'files/explanations/soil/pedology/forming-factors/soil-forming-factors', videoId: '', playlist: '',
          courseFiles: [], books: [], exercises: [], quizzes: [],
        },
        { id: 'weathering', icon: '⛏️', order: 2,
          title:       { en: 'Weathering',    fr: 'Altération',     ar: 'التجوية' },
          description: { en: 'Physical (frost, thermal), Chemical (hydrolysis, oxidation, carbonation), Biological', fr: 'Physiques (gel, thermiques), Chimiques (hydrolyse, oxydation, carbonatation), Biologiques', ar: ' فيزيائية (الصقيع، الحرارة)، كيميائية (التحلل المائي، الأكسدة، الكربنة)، بيولوجية' },
          explanation: 'files/explanations/soil/pedology/weathering/weathering', videoId: '', playlist: '',
          courseFiles: [], books: [], exercises: [], quizzes: [],
        },
        { id: 'Pedogenic Processes', icon: '🥀', order: 3,
          title:       { en: 'Pedogenic Processes',    fr: 'Processus pédogéniques',     ar: 'العمليات التربة' },
          description: { en: 'Eluviation/illuviation, podzolization, laterization, calcification, gleization, salinization', fr: 'Éluviation/Illuviation, Podzolisation, Latérisation, Calcification, Gélisation, Salinisation', ar: ' التحلل/الترسب، التبولد، الترسب، التكلس، الترسب، التملح' },
          explanation: 'files/explanations/soil/pedology/pedogenic-processes/pedogenic-processes', videoId: '', playlist: '',
          courseFiles: [], books: [], exercises: [], quizzes: [],
        },
        { id: 'soil-profile', icon: '📊', order: 4,
          title: { en: 'Soil Profile & Horizons', fr: 'Profil & Horizons', ar: 'القطاع والآفاق' },
          description: { en: 'O, A, E, B, C, R horizons — characteristics and identification.', fr: 'Horizons O, A, E, B, C, R — caractéristiques et identification.', ar: 'الآفاق O وA وE وB وC وR — الخصائص والتعريف.' },
          explanation: 'files/explanations/soil/pedology/soil-profile/soil-profile', videoId: '', playlist: '', courseFiles: [], books: [], exercises: [], quizzes: [],
        },
      ],
    },

    // ── Sub:  Soil Conservation & Management ────────────────────
    {
      id: 'soil-conservation', icon: '🛡️', category: ' soil',
      title:       { en: ' Soil Conservation & Management',     fr: 'Conservation et Gestion des Sols',   ar: 'حماية التربة وإدارتها' },
      description: { en: "Practices and strategies to protect, restore, and sustainably manage soil.", fr: "Pratiques et stratégies pour protéger, restaurer et gérer durablement le sol.", ar: 'ممارسات واستراتيجيات لحماية التربة وإصلاحها وإدارتها باستدامة' },
      books: [
        { icon: '📕',
      title:  { en: 'Soil Erosion and Conservation: 3rd Edition', fr: 'Soil Erosion and Conservation: 3rd Edition', ar: 'Soil Erosion and Conservation: 3rd Edition' },
      author: { en: 'R. P. C. Morgan - 2005', fr: 'R. P. C. Morgan - 2005', ar: 'R. P. C. Morgan - 2005' },
      langs: ['en'], cover:  'files/images/books/soil/SEaC.jpg',
      file:   'https://drive.google.com/file/d/1VVNQwup9KJB2eqSHiAlx7uSov08SMU2G/view?usp=drive_link' },
      ], exercises: [], courseFiles: [],
      topics: [
        { id: 'soil-erosion', icon: '🌊', order: 1,
          title:       { en: 'Soil Erosion',    fr: 'Érosion du Sol',     ar: 'تآكل التربة' },
          description: { en: 'Types (splash, sheet, rill, gully, wind), USLE/RUSLE equation, factors', fr: 'Types (splash, nappe, rigole, ravin, vent), équation USLE/RUSLE, facteurs', ar: ' الأنواع (الرذاذ، الطبقة، الجدول، الأخدود، الرياح)، معادلة USLE/RUSLE، العوامل' },
          explanation: 'files/explanations/soil/conservation/erosion/soil-erosion', videoId: '', playlist: '',
          courseFiles: [], books: [], exercises: [], quizzes: [],
        },
      ],
    },
  ],
});
