// ╔════════════════════════════════════════════════════════════════════╗
// ║  MODULE: STATISTICS                                               ║
// ╚════════════════════════════════════════════════════════════════════╝

modules.push({
  id: 'stat', icon: '📱', category: 'statistics',
  title:       { en: 'Statistics',           fr: 'Statistique',          ar: 'الإحصاء' },
  description: { en: 'Data analysis methods from descriptive statistics to experimental design, applied to life and agricultural sciences.', fr: 'Méthodes d\'analyse des données, de la statistique descriptive aux plans expérimentaux, appliquées aux sciences de la vie et agronomiques.', ar: 'طرق تحليل البيانات من الإحصاء الوصفي إلى التصاميم التجريبية، مطبقة على علوم الحياة والعلوم الزراعية.' },
  books: [
    { icon: '📕',
      title:  { en: 'BIOSTATISTIQUE POUR LES SCIENCES DE LA VIE ET DE LA SANTE', fr: 'BIOSTATISTIQUE POUR LES SCIENCES DE LA VIE ET DE LA SANTE', ar: 'BIOSTATISTIQUE POUR LES SCIENCES DE LA VIE ET DE LA SANTE' },
      author: { en: 'Marc TRIOLA et Mario TRIOLA - 2012', fr: 'Marc TRIOLA et Mario TRIOLA - 2012', ar: 'Marc TRIOLA et Mario TRIOLA - 2012' },
      langs: ['fr'], cover: 'files/images/books/stat/BPSVS.jpg', file: 'https://drive.google.com/file/d/1gwwNyEUYH21SPDAoesk9KUz5ub602xAq/view?usp=sharing' },
  ],
  subModules: [
    // ── 1. Descriptive Statistics ──
    { id: 'descriptive-stat', icon: '📊', category: 'statistics', 
      title:       { en: 'Descriptive Statistics', fr: 'Statistiques Descriptives', ar: 'الإحصاء الوصفي' },
      description: { en: 'Variables, frequency tables, central tendency (mean, median, mode), dispersion (variance, SD), graphical representation', fr: 'Variables, tableaux de fréquences, tendance centrale (moyenne, médiane, mode), dispersion (variance, écart-type), représentation graphique', ar: 'المتغيرات، جداول التكرار، الميل المركزي (المتوسط، الوسيط، الوضع)، التشتت (التباين، الانحراف المعياري)، التمثيل البياني' },
      books: [], courseFiles: [], exercises: [],
      topics: [
        { id: 'variables', icon: '📊', order: 1,
          title:       { en: 'Variables & Data Types', fr: 'Variables et Types de Données', ar: 'المتغيرات وأنواع البيانات' },
          description: { en: 'Qualitative/quantitative, discrete/continuous, scales of measurement', fr: 'Qualitatif/Quantitatif, Discret/Continu, Échelles de Mesure', ar: 'نوعي/كمي، منفصل/مستمر، مقاييس القياس' },
          explanation: 'files/explanations/statistics/descriptive/variables-data/variables-data', videoId: '90J2qTV7rlA', playlist: 'https://www.youtube.com/watch?v=90J2qTV7rlA&list=PLpot-tBGux4nIkVKhaz_77V-u69QWeGf4',
          courseFiles: [], books: [], exercises: [], quizzes: [],
        },
        { id: 'frequency-tables', icon: '📊', order: 2, 
          title: { en: 'Frequency Tables', fr: 'Tableaux de Fréquences', ar: 'جداول التكرارات' }, 
          description: { en: 'Absolute, relative, cumulative frequencies, class intervals.', fr: 'Fréquences absolues, relatives, cumulées, intervalles de classe.', ar: 'التكرارات المطلقة والنسبية والتراكمية وفترات الفئات.' }, 
          explanation: 'files/explanations/statistics/descriptive/frequency-tables/frequency-tables', videoId: '', playlist: '', 
          courseFiles: [], books: [], exercises: [], quizzes: [] },
        { id: 'graphs', icon: '📈', order: 3, 
          title: { en: 'Graphical Representation', fr: 'Représentation Graphique', ar: 'التمثيل البياني' }, 
          description: { en: 'Histograms, bar charts, pie charts, box plots, stem-and-leaf.', fr: 'Histogrammes, diagrammes en barres, camemberts, boîtes à moustaches.', ar: 'المدرجات التكرارية والأعمدة والدائرية والصندوقية.' }, 
          explanation: 'files/explanations/statistics/descriptive/graphs/graphs', videoId: '', playlist: '', 
          courseFiles: [], books: [], exercises: [], quizzes: [] },
        
        { id: 'central-tendency', icon: '📊', order: 4,
          title:       { en: 'Central Tendency', fr: 'Tendance Centrale', ar: 'الميل المركزي' },
          description: { en: 'Mean, median, mode — calculation, properties, when to use each, discrete/continuous, scales of measurement', fr: 'Moyenne, médiane, mode — calcul, propriétés, quand utiliser chacune d\'elles', ar: 'المتوسط، الوسيط، الوضع — الحساب، الخصائص، متى يستخدم كل منها' },
          explanation: 'files/explanations/statistics/descriptive/central-tendency/central-tendency', videoId: '', playlist: 'https://www.youtube.com/watch?v=90J2qTV7rlA&list=PLpot-tBGux4nIkVKhaz_77V-u69QWeGf4',
          courseFiles: [], books: [], exercises: [], quizzes: [],
        },
        { id: 'dispersion', icon: '📊', order: 5,
          title:       { en: 'Dispersion', fr: 'Dispersion', ar: 'التشتت' },
          description: { en: 'Range, variance, standard deviation, coefficient of variation', fr: 'Intervalle, variance, écart type, coefficient de variation', ar: 'النطاق، التباين، الانحراف المعياري، معامل التباين' },
          explanation: 'files/explanations/statistics/descriptive/dispersion/dispersion', videoId: '', playlist: 'https://www.youtube.com/watch?v=90J2qTV7rlA&list=PLpot-tBGux4nIkVKhaz_77V-u69QWeGf4',
          courseFiles: [], books: [], exercises: [], quizzes: [],
        },
      ],
    },
    // ── 2. Probability ──
    { id: 'probability', icon: '📊', category: 'statistics', 
      title:       { en: 'Probability', fr: 'Probabilité', ar: 'الاحتمال' },
      description: { en: 'Probability laws, combinatorics, normal/binomial/Poisson distributions', fr: 'Lois de probabilité, combinatoire, distributions normales/binomiales/de Poisson', ar: 'قوانين الاحتمالات، التوافيق، التوزيعات العادية/الثنائية/بواسون' },
      books: [], courseFiles: [], exercises: [],
      topics: [],
    },
    // ── 3. Inferential Statistics ──
    { id: 'inferential', icon: '📊', category: 'statistics', 
      title:       { en: 'Inferential Statistics', fr: 'Statistiques Inférentielles', ar: 'الإحصاء الاستدلالي' },
      description: { en: 'Sampling, confidence intervals, hypothesis testing (t-test, χ², F-test), ANOVA', fr: 'Échantillonnage, intervalles de confiance, tests d\'hypothèse (test t, χ², test F), ANOVA', ar: 'أخذ العينات، فترات الثقة، اختبار الفرضيات (اختبار t، χ²، اختبار F)، ANOVA' },
      books: [], courseFiles: [], exercises: [],
      topics: [
        { id: 'sampling', icon: '🎯', order: 1, 
          title: { en: 'Sampling', fr: 'Échantillonnage', ar: 'المعاينة' }, 
          description: { en: 'Random, stratified, cluster, systematic; sample size.', fr: 'Aléatoire, stratifié, en grappes, systématique ; taille échantillon.', ar: 'عشوائية، طبقية، عنقودية، منتظمة؛ حجم العينة.' }, 
          explanation: 'files/explanations/statistics/inferential/sampling/sampling', videoId: '', playlist: '', 
          courseFiles: [], books: [], exercises: [], quizzes: [] 
        },
        { id: 'confidence-intervals', icon: '📏', order: 2, 
          title: { en: 'Confidence Intervals', fr: 'Intervalles de Confiance', ar: 'فترات الثقة' }, 
          description: { en: 'Mean, proportion, difference; margin of error.', fr: 'Moyenne, proportion, différence ; marge d\'erreur.', ar: 'المتوسط والنسبة والفرق؛ هامش الخطأ.' }, 
          explanation: 'files/explanations/statistics/inferential/confidence-intervals/confidence-intervals', videoId: '', playlist: '', 
          courseFiles: [], books: [], exercises: [], quizzes: [] 
        },
        { id: 'hypothesis-testing', icon: '⚖️', order: 3, 
          title: { en: 'Hypothesis Testing', fr: 'Tests d\'Hypothèses', ar: 'اختبار الفرضيات' }, 
          description: { en: 'H₀/H₁, type I/II errors, p-value, significance, power.', fr: 'H₀/H₁, erreurs type I/II, p-value, significativité, puissance.', ar: 'H₀/H₁، أخطاء النوع I/II، القيمة p، المعنوية، القوة.' }, 
          explanation: 'files/explanations/statistics/inferential/hypothesis-testing/hypothesis-testing', videoId: '', playlist: '', 
          courseFiles: [], books: [], exercises: [], quizzes: [] 
        },
        { id: 'parametric-tests', icon: '📊', order: 4, 
          title: { en: 'Parametric Tests', fr: 'Tests Paramétriques', ar: 'الاختبارات المعلمية' }, 
          description: { en: 'Student t-test (1-sample, 2-sample, paired), z-test.', fr: 'Test t de Student (1 échantillon, 2 échantillons, apparié), test z.', ar: 'اختبار t (عينة واحدة، عينتين، مزدوج)، اختبار z.' }, 
          explanation: 'files/explanations/statistics/inferential/parametric-tests/parametric-tests', videoId: '', playlist: '', 
          courseFiles: [], books: [], exercises: [], quizzes: [] 
        },
        { id: 'nonparametric-tests', icon: '📋', order: 5, 
          title: { en: 'Non-Parametric Tests', fr: 'Tests Non Paramétriques', ar: 'الاختبارات اللامعلمية' }, 
          description: { en: 'Mann-Whitney, Wilcoxon, Kruskal-Wallis, chi-squared.', fr: 'Mann-Whitney, Wilcoxon, Kruskal-Wallis, khi-deux.', ar: 'مان-ويتني وويلكوكسون وكروسكال-واليس وكاي تربيع.' }, 
          explanation: 'files/explanations/statistics/inferential/nonparametric-tests/nonparametric-tests', videoId: '', playlist: '', 
          courseFiles: [], books: [], exercises: [], quizzes: [] 
        },
        { id: 'anova', icon: '📈', order: 6, 
          title: { en: 'ANOVA', fr: 'ANOVA', ar: 'تحليل التباين' }, 
          description: { en: 'One-way, two-way, F-test, post-hoc (Tukey, Bonferroni).', fr: 'À un facteur, deux facteurs, test F, post-hoc (Tukey, Bonferroni).', ar: 'أحادي وثنائي الاتجاه واختبار F والمقارنات البعدية.' }, 
          explanation: 'files/explanations/statistics/inferential/anova/anova', videoId: '', playlist: '', 
          courseFiles: [], books: [], exercises: [], quizzes: [] 
        },
      ],
    },
    // ── 4. Regression & Correlation ──
    { id: 'regression', icon: '📉', category: 'statistics',
      title:       { en: 'Regression & Correlation', fr: 'Régression & Corrélation', ar: 'الانحدار والارتباط' },
      description: { en: 'Correlation analysis, simple and multiple regression, model validation.',
                     fr: 'Analyse de corrélation, régression simple et multiple, validation de modèle.',
                     ar: 'تحليل الارتباط والانحدار البسيط والمتعدد والتحقق من النموذج.' },
      books: [], courseFiles: [], exercises: [],
      topics: [],
    },
    // ── 5. Experimental Design ──
    { id: 'experimental-design', icon: '🧪', category: 'statistics',
      title:       { en: 'Experimental Design', fr: 'Plans Expérimentaux', ar: 'التصاميم التجريبية' },
      description: { en: 'Principles and types of experimental designs for agricultural research.',
                     fr: 'Principes et types de plans expérimentaux pour la recherche agronomique.',
                     ar: 'مبادئ وأنواع التصاميم التجريبية للبحث الزراعي.' },
      books: [], courseFiles: [], exercises: [],
      topics: [],
    },
  ],
});
